// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS_vOYfoPPa94gyrAY-BO9S8Y3wcy47TM',
    appId: '1:376465477965:web:106aacaa403521b9ce2704',
    messagingSenderId: '376465477965',
    projectId: 'expense-tracker-d697a',
    authDomain: 'expense-tracker-d697a.firebaseapp.com',
    storageBucket: 'expense-tracker-d697a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuqK301Isq71pGVQfblNpRZKjqqSYbI54',
    appId: '1:376465477965:android:cc1940bfdd665261ce2704',
    messagingSenderId: '376465477965',
    projectId: 'expense-tracker-d697a',
    storageBucket: 'expense-tracker-d697a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4U_Dq03Z_OlIzHwMs8sFPaqBBAdwhg5A',
    appId: '1:376465477965:ios:1831b0258ee69278ce2704',
    messagingSenderId: '376465477965',
    projectId: 'expense-tracker-d697a',
    storageBucket: 'expense-tracker-d697a.firebasestorage.app',
    androidClientId: '376465477965-sc7me7t57574621gfn75iduo4ql2hevh.apps.googleusercontent.com',
    iosClientId: '376465477965-hq1ikrpsv315210ru507r921sj91uppc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoSimulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4U_Dq03Z_OlIzHwMs8sFPaqBBAdwhg5A',
    appId: '1:376465477965:ios:1831b0258ee69278ce2704',
    messagingSenderId: '376465477965',
    projectId: 'expense-tracker-d697a',
    storageBucket: 'expense-tracker-d697a.firebasestorage.app',
    androidClientId: '376465477965-sc7me7t57574621gfn75iduo4ql2hevh.apps.googleusercontent.com',
    iosClientId: '376465477965-hq1ikrpsv315210ru507r921sj91uppc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoSimulator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS_vOYfoPPa94gyrAY-BO9S8Y3wcy47TM',
    appId: '1:376465477965:web:0d32111ef5cb7aa8ce2704',
    messagingSenderId: '376465477965',
    projectId: 'expense-tracker-d697a',
    authDomain: 'expense-tracker-d697a.firebaseapp.com',
    storageBucket: 'expense-tracker-d697a.firebasestorage.app',
  );
}
